### ISSUE TITLE
Not Able to convert ASC to CSV , Getting no such file or directory 

### ISSUE THREAD

**Issue by Olayiwolabolaji** [XinsongDu/FN_Mortality#1]
Hi 
When I tried to run the code, I keep getting that No such file or directory. I hope someone can help

Here is the code:
python src/sas2csv.py -d {/Users/olayiwolabolaji/Downloads/HCUP/NIS_2017_Severity.ASC} -l {/Users/olayiwolabolaji/Downloads/HCUP/SASLoad_NIS_2017_Severity.SAS} -o {/Users/olayiwolabolaji/Downloads/HCUP} -y {2017}

HERE IS THE ERROR

[2020-05-04 01:26:44,837]: INFO: 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 14:10:59) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Traceback (most recent call last):
  File "src/sas2csv.py", line 56, in <module>
    '../logs/sas2csv_%s.log'%(os.path.split(os.path.basename(args.df))[1][0:-4]), maxBytes=100 * 1024 * 1024, backupCount=10)
  File "/Users/olayiwolabolaji/.pyenv/versions/miniconda2-latest/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/Users/olayiwolabolaji/.pyenv/versions/miniconda2-latest/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/Users/olayiwolabolaji/.pyenv/versions/miniconda2-latest/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/olayiwolabolaji/.pyenv/versions/miniconda2-latest/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/Users/olayiwolabolaji/logs/sas2csv_NIS_2017_Severity..log'

**Comment by XinsongDu** [comment]
@Olayiwolabolaji Not sure your computer setting or working directory information, but the simplest way to solve this can be removing line 55-57 from `sas2csv.py`. Also, please also keep in mind that:
1. The code has been successfully run for 2007-2015 (third quarter) data, this cannot 100% assure that it will work for 2017 data.
2. It may take several hours to finish running.

**Comment by Olayiwolabolaji** [comment]
Thanks @XinsongDu , Please How will I remove line 55-57?

**Comment by XinsongDu** [comment]
@Olayiwolabolaji I assume you have cloned the repository or downloaded `sas2csv.py`. You can do it on your own computer (e.g., use a text editor)

**Comment by Olayiwolabolaji** [comment]
Yes, I have cloned the repository. I am kinda new to python, I will appreciate if your can briefly explain how I will go about it . Thanks

**Comment by XinsongDu** [comment]
The code is designed based on my computer setting. I recommend you to use [sublime](https://www.sublimetext.com/) to edit it according to your computer setting. Long in short, you can try to remove line 55-57:
```
handler = logging.handlers.RotatingFileHandler(
        '../logs/sas2csv_%s.log'%(os.path.split(os.path.basename(args.df))[1][0:-4]), maxBytes=100 * 1024 * 1024, backupCount=10)
    logger.addHandler(handler)
```

**Comment by Olayiwolabolaji** [comment]
Thank, I have a sublime.
My question is where would that code go into or how will I use sublime to edit it. 
Thanks

**Comment by XinsongDu** [comment]
No problem.

1. Open sas2csv.py with sublime
2. Remove line 55-57
3. Save

**Comment by Olayiwolabolaji** [comment]
This is what I get now 

[2020-05-04 02:46:58,704]: INFO: 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 14:10:59) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
[2020-05-04 02:46:58,719]: INFO: file path: {~Downloads/HCUP}/NIS_2017_Severity.csv
Traceback (most recent call last):
  File "src/sas2csv.py", line 56, in <module>
    converter(args.df, args.lf, args.output, args.year)
  File "src/sas2csv.py", line 28, in converter
    meta_df = pyhcup.meta_from_sas(loadfile)
  File "/Users/olayiwolabolaji/.pyenv/versions/miniconda2-latest/lib/python2.7/site-packages/pyhcup/sas.py", line 14, in meta_from_sas
    concatenated = ''.join([x for x in open(target)])
IOError: [Errno 2] No such file or directory: '{/Users/olayiwolabolaji/Downloads/HCUP/SASLoad_NIS_2017_Severity.SAS}'

**Comment by XinsongDu** [comment]
@Olayiwolabolaji Please contact my supervisor Dr. Dominick Lemas (https://hobi.med.ufl.edu/lemas-dominick/) if you want any type of collaboration. He is also the corresponding author of the paper. Thanks

**Comment by Olayiwolabolaji** [comment]
Thank you @XinsongDu . I will contact him.
